### ISSUE TITLE
Access is denied.

### ISSUE THREAD

**Issue by RiftSTW** [EZFNDEV/UE4AESKeyFinder#1]
Not sure what caused this but I did try having it open as admin and I got the same error.

![image](https://user-images.githubusercontent.com/33435468/115130320-889f4100-9fb4-11eb-88e2-4912adc2ddd7.png)

**Comment by LievreAI** [comment]
i face with that too how i can fix it @RiftSTW

**Comment by RiftSTW** [comment]
> i face with that too how i can fix it @RiftSTW 

I have no fix for it
