### ISSUE TITLE
help how download source from github

### ISSUE THREAD

**Issue by Fischsalat** [EZFNDEV/UE4AESKeyFinder#2]
pls help

**Comment by Fischsalat** [comment]
no why, help! how download?

**Comment by Fischsalat** [comment]
plz tell

**Comment by 1337doener** [comment]
> plz tell

pls shut up men me no tell to noob how to compile cs code men

**Comment by 1337doener** [comment]
pls gogle how 2 compil csharp code men

**Comment by Fischsalat** [comment]
Are you trolling too, or are you retarded?

**Comment by 1337doener** [comment]
men me never troll me alway retardo

**Comment by 1337doener** [comment]
fuck you lupus

**Comment by Fischsalat** [comment]
:(

**Comment by Kian738** [comment]
### Lmao ihr seid beide deutsch but okay
