### ISSUE TITLE
No instruction

### ISSUE THREAD

**Issue by lynrayy** [EZFNDEV/UE4AESKeyFinder#36]
How to use it what the fuck? It closes instantly after start (UEAESKeyFinder.exe)

**Comment by Zaphirez** [comment]
Same problem here... just crashes on launch. i can see it for 1 millisecond and then it just dissapears

**Comment by DogancanYr** [comment]
Open cmd and drag it there then hit enter.

**Comment by yusonisharper** [comment]
Install Framework Microsoft.NETCore.App version 3.1.0 x64 to resolve this issue: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.0-windows-x64-installer
