### ISSUE TITLE
App Issue

### ISSUE THREAD

**Issue by DevlinCPerks** [EZFNDEV/UE4AESKeyFinder#38]
This is my first time using this and for some reason, it just closes immediately when i open it. not sure why. Do you know why this is happening?

**Comment by yusonisharper** [comment]
Install Framework Microsoft.NETCore.App version 3.1.0 x64 to resolve this issue: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.0-windows-x64-installer
